version: "2"

services:
    lemp-nginx:
        image: nginx:alpine
        container_name: lemp-nginx-causelabs
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html:rw
            - ./containers/lemp-nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - lemp-network
        links:
            - lemp-php

    lemp-mariadb:
        image: mariadb:latest
        container_name: lemp-mariadb-causelabs
        volumes:
            - lemp-volume-mariadb:/var/lib/mysql
        networks:
            - lemp-network
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: causelabs
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: dbpassword
            MYSQL_ROOT_PASSWORD: dbrootpassword

    lemp-php:
        build: ./containers/lemp-php/
        container_name: lemp-php-causelabs
        volumes:
            - ./:/var/www/html
        networks:
            - lemp-network
        links:
            - lemp-mariadb
        environment:
            ENVIRONMENT: development

networks:
    lemp-network:
        driver: bridge

volumes:
    lemp-volume-mariadb:
